#Retrieve all information about the vehicles available in the dealership.
SELECT * FROM Brands;
SELECT * FROM Customer;
SELECT * FROM Deal;
SELECT * FROM Dealership;
SELECT * FROM Insaurance;
SELECT * FROM Manager;
SELECT * FROM Region;
SELECT * FROM Sales_agent;
SELECT * FROM Vehicle;

#Find the total number of vehicles in the all the Showrooms.
SELECT COUNT(*) FROM Vehicle; 

#List the details of the distinct top three most expensive Scooters in all showrooms.
SELECT DISTINCT(price) FROM Vehicle
ORDER BY Price DESC
LIMIT 3;

#Retrieve the names and contact information of all customers who have purchased a vehicle.
SELECT CFirstName, CLastName, Phone_number, Email FROM Customer
WHERE CustomerID IN (SELECT DISTINCT(d.customerID) FROM Customer c  JOIN Deal d ON c.CustomerID  AND d.DealID);

#Find the average price of vehicles in all showrooms.
SELECT AVG(price) FROM Vehicle;

#List the names of sales agents along with the total number of deals they have closed.
SELECT AFirstName, ALastName, COUNT(*) AS TotalDeals FROM Sales_Agent 
JOIN DEAL ON Sales_agent.AgentID = Deal.AgentID
GROUP BY AFirstName, ALastName;

#Retrieve the details of the most recent deal, including the vehicle, customer, and agent information.
SELECT * FROM Deal WHERE DealDate = (SELECT MAX(DealDate) FROM Deal);

#Find the total revenue generated by each dealership from all deals.
SELECT  DealershipName , SUM(price) Totalrevenue FROM dealership d JOIN Vehicle v ON d.DealershipID = v.dealershipID
GROUP BY DealershipName
ORDER BY Totalrevenue DESC;

#Retrieve the details of vehicles that have not been sold (not included in any deal).
SELECT * FROM Vehicle  WHERE vehicleID NOT IN
(SELECT VehicleID FROM deal);

#List the names of customers who purchased a vehicle along with the model and make of the vehicle.
SELECT CfirstName, CLastName, Make, Model FROM Vehicle 
JOIN deal ON Vehicle.VehicleID = deal.VehicleID
JOIN Customer ON Customer.customerID = Deal.customerID;

#Calculate the total commission earned by each sales agent in the last quarter. 
#Assume that the commission is 5% of the total deal amount. Include the agent's name and total commission.
SELECT Deal.AgentID, AFirstName, ALastName, SUM(price * 0.05) AS Total_Commission  FROM Sales_agent 
JOIN Deal ON Sales_Agent.AgentID = Deal.AgentID
JOIN Vehicle ON Deal.VehicleID = Vehicle.VehicleID
WHERE DealDate <= '2022-12-20' AND DealDate >= '2022-11-08'
GROUP BY Deal.AgentID, AFirstName, ALastName;


#Identify the top 3 most profitable vehicle models by calculating the total revenue generated from deals for each model.
SELECT Model, SUM(price) AS Total_revenue FROM Vehicle 
JOIN Deal ON Deal.VehicleID = Vehicle.VehicleID
GROUP BY Model
ORDER BY Total_revenue DESC
LIMIT 3;

#Calculate the total number of deals closed for each vehicle Make. 
#Display the Make and the total number of deals, even if no deals have been made for that Make.
SELECT Make, COUNT(Deal.VehicleID) FROM Deal
JOIN Vehicle ON Deal.VehicleID = Vehicle.VehicleID
GROUP BY Make



    

 





 












